<?php
    $this->headScript()->appendFile('/js/jquery-1.8.2.min.js');
    $this->headScript()->appendFile('/js/uploader/js/vendor/jquery.ui.widget.js');
    $this->headLink()->appendStylesheet('/js/uploader/css/style.css');
    $this->headLink()->appendStylesheet('http://blueimp.github.com/cdn/css/bootstrap.min.css');
    $this->headLink()->appendStylesheet('/js/uploader/css/jquery.fileupload-ui.css');
?>

<div id="view-content">
    <?php if (!isset($this->data)) 
	    echo $this->form;
	else if ($this->step == 1): ?>
	<a class="btn_next" href="/console/issues/cover/?step=2&issue=<?php echo $this->issue; ?>&new=1" style="display:none"> Dalej </a>
	<form id="fileupload" action="/js/uploader/server/php/index.php" method="POST" enctype="multipart/form-data">
	    <input type="hidden" name="MAX_FILE_SIZE" value="20971520" />
		<div class="row fileupload-buttonbar">
		    <div class="span7">
			<!-- The fileinput-button span is used to style the file input field as button -->
			<span class="btn btn-success fileinput-button">
			    <i class="icon-plus icon-white"></i>
			    <span>Wybierz pliki</span>
			    <input type="file" name="files[]" multiple>
			</span>
<!--			<button type="submit" class="btn btn-primary start">
			    <i class="icon-upload icon-white"></i>
			    <span>Start</span>
			</button>-->
			<button type="reset" class="btn btn-warning cancel">
			    <i class="icon-ban-circle icon-white"></i>
			    <span>Anuluj</span>
			</button>
			<button type="button" class="btn btn-danger">
			    <i class="icon-trash icon-white"></i>
			    <span>Usuń</span>
			</button>
			<input type="checkbox" class="toggle">
		    </div>
		    <!-- The global progress information -->
		    <div class="span5 fileupload-progress fade">
			<!-- The global progress bar -->
			<div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
			    <div class="bar" style="width:0%;"></div>
			</div>
			<!-- The extended global progress information -->
			<div class="progress-extended">&nbsp;</div>
		    </div>
		</div>
		<!-- The loading indicator is shown during file processing -->
		<div class="fileupload-loading"></div>
		<br>
		<!-- The table listing the files available for upload/download -->
		<table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
		<input type="hidden" name="dir" value="<?php echo $this->issue; ?>" id="dir">
	    </form>
	    <a class="btn_next" href="/console/issues/new/?step=2&issue=<?php echo $this->issue; ?>&new=1;" style="display:none"> Dalej </a>

	    <!-- The template to display files available for upload -->
	    <script id="template-upload" type="text/x-tmpl">
	    {% for (var i=0, file; file=o.files[i]; i++) { %}
		<tr class="template-upload fade">
		    <td class="preview"><span class="fade"></span></td>
		    <td class="name"><span>{%=file.name%}</span></td>
		    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
		    {% if (file.error) { %}
			<td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
		    {% } else if (o.files.valid && !i) { %}
			<td>
			    <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
			</td>
			<td class="start">{% if (!o.options.autoUpload) { %}
			    <button class="btn btn-primary">
				<i class="icon-upload icon-white"></i>
				<span>{%=locale.fileupload.start%}</span>
			    </button>
			{% } %}</td>
		    {% } else { %}
			<td colspan="2"></td>
		    {% } %}
		    <td class="cancel">{% if (!i) { %}
			<button class="btn btn-warning">
			    <i class="icon-ban-circle icon-white"></i>
			    <span>{%=locale.fileupload.cancel%}</span>
			</button>
		    {% } %}</td>
		</tr>
	    {% } %}
	    </script>
	    <!-- The template to display files available for download -->
	    <script id="template-download" type="text/x-tmpl">
	    {% for (var i=0, file; file=o.files[i]; i++) { %}
		<tr class="template-download fade">
		    {% if (file.error) { %}
			<td></td>
			<td class="name"><span>{%=file.name%}</span></td>
			<td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
			<td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
		    {% } else { %}
			<td class="preview">{% if (file.thumbnail_url) { %}
			    <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
			{% } %}</td>
			<td class="name">
			    <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
			</td>
			<td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
			<td colspan="2"></td>
		    {% } %}
		    <td class="delete">
			<button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
			    <i class="icon-trash icon-white"></i>
			    <span>{%=locale.fileupload.destroy%}</span>
			</button>
			<input type="checkbox" name="delete" value="1">
		    </td>
		</tr>
	    {% } %}
	    </script>	

	    <script>
	    $(function () {
		$('#fileupload').fileupload({
		    dataType: 'json',
		    autoUpload: true,
		    completed: function(){
			    $('.btn_next').show();
			},
		    start: function(){
			    $('.btn_next').hide();
			}
		});
	    });
	    </script>

	    <script src="http://blueimp.github.com/JavaScript-Templates/tmpl.min.js"></script>
	    <!-- The basic File Upload plugin -->
	    <script src="/js/uploader/js/jquery.fileupload.js"></script>
	    <!-- The File Upload file processing plugin -->
	    <script src="/js/uploader/js/jquery.fileupload-fp.js"></script>
	    <!-- The File Upload user interface plugin -->
	    <script src="/js/uploader/js/jquery.fileupload-ui.js"></script>
	    <!-- The localization script -->
	    <script src="/js/uploader/js/locale.js"></script>
	    <!-- The main application script -->
	    <script src="/js/uploader/js/main.js"></script>
	<?php endif; ?>	
</div>