<?php
    $this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
    $this->headScript()->appendFile('/js/JSCal2-1.9/src/js/jscal2.js');
    $this->headScript()->appendFile('/js/JSCal2-1.9/src/js/lang/pl.js');
    $this->headLink()->appendStylesheet('/js/JSCal2-1.9/src/css/jscal2.css');
?>
    <?php echo $this->form; ?>
    <script type="text/javascript">//<![CDATA[
    Calendar.setup({
        inputField : "date_from",
        trigger    : "date_from",
        onSelect   : function() { this.hide() },
        dateFormat : "%Y-%m-%d"
    });
    Calendar.setup({
        inputField : "date_to",
        trigger    : "date_to",
        onSelect   : function() { this.hide() },
        dateFormat : "%Y-%m-%d"
    });
    //]]>

    CKEDITOR.replace("html",{
        skin:"v2",
        filebrowserImageUploadUrl : 'ckeditor/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images'
    });
    CKEDITOR.on('instanceReady',type_change);
    </script> 