<div id="view-content">
    <h3>Banery</h3>
    <a class="new" href="/console/baners/new/">Nowy</a>
    <table cellspacing="0" cellpadding="2" border=1>
        <tr><th>L.P.</th><th>Nazwa</th><th>Położenie</th><th>Typ</th><th>Aktywny</th><th>Akcje</th></tr>
        <?php $i=1; foreach ($this->baners as $row):
	echo '<tr><td>'.$i.'</td><td>'.$row['name'].'</td><td>';
	echo ($row['position']=='top')?'<img src="/ico/ban_top.png" class="baner_img">Górny':'<img src="/ico/ban_left.png" class="baner_img">Lewy';
	echo '</td><td>';
	switch ($row['type']){
	    case'html':{
	    echo '<img src="/ico/globe_link.png" class="mime">HTML';
	    break;
	    }
	    case'img':{
	    echo '<img src="/ico/mime_jpg.png" class="mime">Obraz';
	    break;
	    }
	    case'swf':{
	    echo '<img src="/ico/mime_swf.png" class="mime">Flash';
	    break;
	    }
	}
	echo'</td><td><img class="mime" src="/ico/';
	echo ($row['active']==1)?'ok.png">Tak</td><td><a href="/console/baners/activate/?active=0&id='.$row['id'].'" class="deactivate">Dezaktywuj</a>':'no.png">Nie</td><td><a href="/console/baners/activate/?active=1&id='.$row['id'].'" class="activate">Aktywuj</a>';
	echo '&nbsp;<a href="/console/baners/edit/?id='.$row['id'].'" class="edit">Edytuj</a>&nbsp;<a href="/console/baners/delete/?id='.$row['id'].'" class="delete">Usuń</a></td></tr>';
        $i++;
	endforeach;?>
    </table>
</div>