
<div id="left_column">
    <div class="b-right" style="clear:left;"><h2><?php echo $this->params('archive_name')?></h2></div>
    <div id="links" style="text-align:right !important;padding-right:25px;">
	<?php foreach ($this->archivalArr as $issue):  ?>
	    <a href="/issue/show?id=<?php echo $issue['ordinal_no'].'">'.$issue['number'].'('.$issue['ordinal_no'].')/'.$issue['year']; ?></a><br>
	<?php endforeach; ?>
    </div>
</div>
<div id="content">
    <?php foreach ($this->archivalArr as $issue): ?>
	<div class="coop" style="width:150px !important"><center><a href="/issue/show?id=<?php echo $issue['ordinal_no']; ?>"><IMG SRC="/covers/<?php echo $issue['ordinal_no']; ?>_3.jpg" WIDTH="69" HEIGHT="99" BORDER="0"><br><br><?php echo $issue['number'].'('.$issue['ordinal_no'].')/'.$issue['year']?></a></center></div>
    <?php endforeach; ?>
</div>