<hmtl>
    <head>
	<title>Konsola</title>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<link rel="stylesheet" type="text/css" href="/css/cons.css">
	<?php
	    echo $this->headScript();
	    echo $this->headTitle();
	?>
    </head>
    <body>
	<div style="width:100%;border:none;overflow:hidden;">
	    <a href="/console/"><img src="/img/logo.png" style="float:left; margin-right:300px;border:none;"width="250"></a>
	    <h1 style="width:200px; float:left;">Konsola</h1>
	    <span style="float:right;">Zalogowany użytkownik: <?php echo $this->admin['imie'].' '.$this->admin['nazwisko']; ?></span>
	</div>
	<div style="width:300px;float:left;clear:left;margin-top:20px;">
	    <h3>Treść</h3>
	    <a href="/console/index/list-issues">Numery</a><br>
	    <a href="/console/index/list-static">Strony statyczne</a><br>
	    <a href="/console/index/coop">Kooperanci</a><br>
	    <a href="/console/index/baners">Banery</a><br>
	    <a href="/console/index/upload">Upload</a><br>
	    <br>
	    <h3>Ustawienia</h3>
	    <a href="/console/index/params">Parametry</a><br>
	    <a href="/console/index/admins">Administratorzy</a><br>
	    <!--<a href="http:\\www.zagroda.atomnet.pl\index.php" target="blank">Strona główna Zagrody</a></br>--> 
	    <br>
	    <a href="/" target="blank">Strona główna Zagrody</a></br>
	    <a href="/console/index/logout">Wyloguj</a><br>
	</div>
	<div id="content" style="float:left;margin-top:20px;overflow:none;">
	    <?php echo $this->layout()->content;?>
	</div>
    </body>
</html>